### ISSUE TITLE
i am getting key error

### ISSUE THREAD

**Issue by hassan542** [rkhozinov/fuzzy_metric#1]
Traceback (most recent call last):
  File "new.py", line 46, in <module>
    system.calculate(my_input,output)
  File "/usr/local/lib/python2.7/dist-packages/fuzzy/System.py", line 93, in calculate
    self.defuzzify(output)
  File "/usr/local/lib/python2.7/dist-packages/fuzzy/System.py", line 76, in defuzzify
    output[name] = self.variables[name].getValue()
KeyError: 'output'

**Comment by hassan542** [comment]
please help
